package io.github.mcclauneck.mceconomy.common.database.postgresql;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import io.github.mcclauneck.mceconomy.api.database.IMCEconomyDB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.CompletableFuture;

/**
 * PostgreSQL-backed implementation of the asynchronous MCEconomy database contract.
 */
public class MCEconomyPostgreSQL implements IMCEconomyDB {

    /**
     * The pooled JDBC data source used for PostgreSQL access.
     */
    private final HikariDataSource dataSource;

    /**
     * Creates a new PostgreSQL economy database adapter.
     *
     * @param dbUser the database username
     * @param dbPass the database password
     * @param dbHost the database host
     * @param dbName the database name
     * @param dbPort the database port, or blank to use the PostgreSQL default
     * @param dbSsl whether SSL should be enabled
     */
    public MCEconomyPostgreSQL(String dbUser, String dbPass, String dbHost, String dbName, String dbPort, boolean dbSsl) {
        String port = (dbPort == null || dbPort.isBlank()) ? "5432" : dbPort.trim();

        HikariConfig config = new HikariConfig();
        String sslParam = dbSsl ? "?sslmode=verify-full" : "?sslmode=disable";
        config.setJdbcUrl("jdbc:postgresql://" + dbHost + ":" + port + "/" + dbName + sslParam);
        config.setUsername(dbUser);
        config.setPassword(dbPass);
        config.setMaximumPoolSize(10);
        config.setMinimumIdle(2);
        config.setConnectionTimeout(30000);
        config.setLeakDetectionThreshold(10000);

        this.dataSource = new HikariDataSource(config);

        try {
            createTables();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates the currencies and account tables used by the new currency-id schema.
     *
     * @throws SQLException if table creation fails
     */
    private void createTables() throws SQLException {
        String currencySql = "CREATE TABLE IF NOT EXISTS mceconomy_currencies ("
                + "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name_display VARCHAR(255) NOT NULL, "
                + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
        String accountSql = "CREATE TABLE IF NOT EXISTS mceconomy_account ("
                + "account_type VARCHAR(32) NOT NULL, "
                + "account_id VARCHAR(36) NOT NULL, "
                + "coin_type INT NOT NULL, "
                + "amount BIGINT NOT NULL DEFAULT 0, "
                + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                + "PRIMARY KEY (account_type, account_id, coin_type), "
                + "FOREIGN KEY (coin_type) REFERENCES mceconomy_currencies(id) ON DELETE CASCADE)";

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute(currencySql);
            stmt.execute(accountSql);
        }
    }

    /**
     * Retrieves the balance for the requested account and currency.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to read
     * @return a future containing the current balance
     */
    @Override
    public CompletableFuture<Long> getBalance(String accountType, String accountId, int currencyId) {
        return CompletableFuture.supplyAsync(() -> getBalanceSync(accountType, accountId, currencyId));
    }

    /**
     * Sets the balance for the requested account and currency.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the new balance
     * @return a future that resolves to {@code true} when the update succeeds
     */
    @Override
    public CompletableFuture<Boolean> setBalance(String accountType, String accountId, int currencyId, long amount) {
        return CompletableFuture.supplyAsync(() -> setBalanceSync(accountType, accountId, currencyId, amount));
    }

    /**
     * Adds to the balance for the requested account and currency.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the amount to add
     * @return a future that resolves to {@code true} when the update succeeds
     */
    @Override
    public CompletableFuture<Boolean> addBalance(String accountType, String accountId, int currencyId, long amount) {
        return CompletableFuture.supplyAsync(() -> addBalanceSync(accountType, accountId, currencyId, amount));
    }

    /**
     * Subtracts from the balance for the requested account and currency.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the amount to subtract
     * @return a future that resolves to {@code true} when the subtraction succeeds
     */
    @Override
    public CompletableFuture<Boolean> subtractBalance(String accountType, String accountId, int currencyId, long amount) {
        return CompletableFuture.supplyAsync(() -> subtractBalanceSync(accountType, accountId, currencyId, amount));
    }

    /**
     * Transfers balance between two accounts for the requested currency.
     *
     * @param senderType the sender account type
     * @param senderId the sender account identifier
     * @param receiverType the receiver account type
     * @param receiverId the receiver account identifier
     * @param currencyId the currency identifier to transfer
     * @param amount the amount to transfer
     * @return a future that resolves to {@code true} when the transfer succeeds
     */
    @Override
    public CompletableFuture<Boolean> transferBalance(
            String senderId,
            String senderType,
            String receiverId,
            String receiverType,
            int currencyId,
            long amount
    ) {
        return CompletableFuture.supplyAsync(() ->
                transferBalanceSync(senderType, senderId, receiverType, receiverId, currencyId, amount)
        );
    }

    /**
     * Ensures the requested account and currency row exists.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to ensure
     * @return a future that resolves to {@code true} when the row exists
     */
    @Override
    public CompletableFuture<Boolean> ensureAccountExists(String accountType, String accountId, int currencyId) {
        return CompletableFuture.supplyAsync(() -> {
            try (Connection conn = dataSource.getConnection()) {
                return ensureAccountExists(conn, accountType, accountId, currencyId);
            } catch (SQLException e) {
                e.printStackTrace();
                return false;
            }
        });
    }

    /**
     * Reads the current balance using a direct JDBC query.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to read
     * @return the current balance, or {@code 0} when no row is available
     */
    private long getBalanceSync(String accountType, String accountId, int currencyId) {
        if (currencyId <= 0) {
            return 0L;
        }

        try (Connection conn = dataSource.getConnection()) {
            if (!ensureAccountExists(conn, accountType, accountId, currencyId)) {
                return 0L;
            }

            String sql = "SELECT amount FROM mceconomy_account WHERE account_type = ? AND account_id = ? AND coin_type = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, accountType);
                pstmt.setString(2, accountId);
                pstmt.setInt(3, currencyId);
                try (ResultSet rs = pstmt.executeQuery()) {
                    return rs.next() ? Math.max(0L, rs.getLong("amount")) : 0L;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return 0L;
        }
    }

    /**
     * Stores an absolute balance using a direct JDBC update.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the new balance
     * @return {@code true} when the update succeeds
     */
    private boolean setBalanceSync(String accountType, String accountId, int currencyId, long amount) {
        if (amount < 0 || currencyId <= 0) {
            return false;
        }

        try (Connection conn = dataSource.getConnection()) {
            if (!ensureAccountExists(conn, accountType, accountId, currencyId)) {
                return false;
            }

            String sql = "UPDATE mceconomy_account SET amount = ?, updated_at = CURRENT_TIMESTAMP "
                    + "WHERE account_type = ? AND account_id = ? AND coin_type = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setLong(1, amount);
                pstmt.setString(2, accountType);
                pstmt.setString(3, accountId);
                pstmt.setInt(4, currencyId);
                pstmt.executeUpdate();
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Increments the current balance using a direct JDBC update.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the amount to add
     * @return {@code true} when the update succeeds
     */
    private boolean addBalanceSync(String accountType, String accountId, int currencyId, long amount) {
        if (amount <= 0 || currencyId <= 0) {
            return false;
        }

        try (Connection conn = dataSource.getConnection()) {
            if (!ensureAccountExists(conn, accountType, accountId, currencyId)) {
                return false;
            }

            String sql = "UPDATE mceconomy_account SET amount = amount + ?, updated_at = CURRENT_TIMESTAMP "
                    + "WHERE account_type = ? AND account_id = ? AND coin_type = ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setLong(1, amount);
                pstmt.setString(2, accountType);
                pstmt.setString(3, accountId);
                pstmt.setInt(4, currencyId);
                pstmt.executeUpdate();
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Decrements the current balance using a guarded JDBC update.
     *
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to update
     * @param amount the amount to subtract
     * @return {@code true} when enough balance exists and the update succeeds
     */
    private boolean subtractBalanceSync(String accountType, String accountId, int currencyId, long amount) {
        if (amount <= 0 || currencyId <= 0) {
            return false;
        }

        try (Connection conn = dataSource.getConnection()) {
            if (!ensureAccountExists(conn, accountType, accountId, currencyId)) {
                return false;
            }

            String sql = "UPDATE mceconomy_account SET amount = amount - ?, updated_at = CURRENT_TIMESTAMP "
                    + "WHERE account_type = ? AND account_id = ? AND coin_type = ? AND amount >= ?";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setLong(1, amount);
                pstmt.setString(2, accountType);
                pstmt.setString(3, accountId);
                pstmt.setInt(4, currencyId);
                pstmt.setLong(5, amount);
                return pstmt.executeUpdate() > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Performs a transactional transfer between two accounts.
     *
     * @param senderType the sender account type
     * @param senderId the sender account identifier
     * @param receiverType the receiver account type
     * @param receiverId the receiver account identifier
     * @param currencyId the currency identifier to transfer
     * @param amount the amount to transfer
     * @return {@code true} when the transaction commits successfully
     */
    private boolean transferBalanceSync(
            String senderType,
            String senderId,
            String receiverType,
            String receiverId,
            int currencyId,
            long amount
    ) {
        if (amount <= 0 || currencyId <= 0) {
            return false;
        }

        try (Connection conn = dataSource.getConnection()) {
            boolean previousAutoCommit = conn.getAutoCommit();
            conn.setAutoCommit(false);
            try {
                if (!ensureAccountExists(conn, senderType, senderId, currencyId)
                        || !ensureAccountExists(conn, receiverType, receiverId, currencyId)) {
                    conn.rollback();
                    return false;
                }

                String withdrawSql = "UPDATE mceconomy_account SET amount = amount - ?, updated_at = CURRENT_TIMESTAMP "
                        + "WHERE account_type = ? AND account_id = ? AND coin_type = ? AND amount >= ?";
                try (PreparedStatement withdraw = conn.prepareStatement(withdrawSql)) {
                    withdraw.setLong(1, amount);
                    withdraw.setString(2, senderType);
                    withdraw.setString(3, senderId);
                    withdraw.setInt(4, currencyId);
                    withdraw.setLong(5, amount);
                    if (withdraw.executeUpdate() == 0) {
                        conn.rollback();
                        return false;
                    }
                }

                String depositSql = "UPDATE mceconomy_account SET amount = amount + ?, updated_at = CURRENT_TIMESTAMP "
                        + "WHERE account_type = ? AND account_id = ? AND coin_type = ?";
                try (PreparedStatement deposit = conn.prepareStatement(depositSql)) {
                    deposit.setLong(1, amount);
                    deposit.setString(2, receiverType);
                    deposit.setString(3, receiverId);
                    deposit.setInt(4, currencyId);
                    deposit.executeUpdate();
                }

                conn.commit();
                return true;
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(previousAutoCommit);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Ensures the account row exists for the requested account and currency.
     *
     * @param conn the active SQL connection
     * @param accountType the logical account type
     * @param accountId the unique account identifier
     * @param currencyId the currency identifier to ensure
     * @return {@code true} when the account row exists
     * @throws SQLException if the upsert fails
     */
    private boolean ensureAccountExists(Connection conn, String accountType, String accountId, int currencyId) throws SQLException {
        if (currencyId <= 0) {
            return false;
        }

        ensureCurrencyExists(conn, currencyId);
        String sql = "INSERT INTO mceconomy_account (account_type, account_id, coin_type, amount) VALUES (?, ?, ?, 0) "
                + "ON CONFLICT (account_type, account_id, coin_type) DO NOTHING";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, accountType);
            pstmt.setString(2, accountId);
            pstmt.setInt(3, currencyId);
            pstmt.executeUpdate();
            return true;
        }
    }

    /**
     * Ensures the referenced currency row exists before account writes occur.
     *
     * @param conn the active SQL connection
     * @param currencyId the currency identifier to ensure
     * @throws SQLException if the currency upsert fails
     */
    private void ensureCurrencyExists(Connection conn, int currencyId) throws SQLException {
        String sql = "INSERT INTO mceconomy_currencies (id, name_display) VALUES (?, ?) ON CONFLICT (id) DO NOTHING";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, currencyId);
            pstmt.setString(2, defaultCurrencyName(currencyId));
            pstmt.executeUpdate();
        }
    }

    /**
     * Builds the fallback display name used for auto-created currency rows.
     *
     * @param currencyId the currency identifier
     * @return the generated display name
     */
    private String defaultCurrencyName(int currencyId) {
        return "Currency " + currencyId;
    }

    /**
     * Closes the JDBC connection pool.
     */
    @Override
    public void close() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
        }
    }
}
